output:
  root: data/Energy_Core_Position_Estimate.merge_example_v1.yolov8

inputs:
  - name: v7
    root: data/Energy_Core_Position_Estimate.v7i.yolov8
    ratios:
      train: 0.10
      valid: 0.20
      test: 0.20
  - name: v8
    root: data/Energy_Core_Position_Estimate.v8-add-blue-real-marker.yolov8
    ratios:
      train: 0.10
      valid: 0.20
      test: 0.20

sampling:
  seed: 52

merge:
  rename_mode: prefix_input_name

postprocess:
  scale_balance:
    enabled: false
